/*
 * MechMind Program
 * Author: Kizmit99
 * License: CC BY-NC-SA 4.0
 *
 * This source code is open-source for non-commercial use. 
 * For commercial use, please obtain a license from the author.
 * For more information, visit https://github.com/kizmit99/MechMind
 */

#include "droid/controller/MechRingController.h"

#define CONFIG_KEY_MECHRING_ACTIVE_TIMEOUT      "activeTimeout"
#define CONFIG_KEY_MECHRING_INACTIVE_TIMEOUT    "inactiveTimeout"
#define CONFIG_KEY_MECHRING_DEADBAND_X          "DeadbandX"
#define CONFIG_KEY_MECHRING_DEADBAND_Y          "DeadbandY"

#define CONFIG_DEFAULT_MECHRING_ACTIVE_TIMEOUT   200
#define CONFIG_DEFAULT_MECHRING_INACTIVE_TIMEOUT 10000
#define CONFIG_DEFAULT_MECHRING_DEADBAND         16

namespace {
    // Button bitmask constants (v2.0 protocol - 16-bit)
    const uint16_t BTN_A          = 0x0001;  // Bit 0
    const uint16_t BTN_B          = 0x0002;  // Bit 1
    const uint16_t BTN_C          = 0x0004;  // Bit 2
    const uint16_t BTN_D          = 0x0008;  // Bit 3
    const uint16_t BTN_UP         = 0x0010;  // Bit 4 (virtual, generated by ring)
    const uint16_t BTN_DOWN       = 0x0020;  // Bit 5 (virtual, generated by ring)
    const uint16_t BTN_LEFT       = 0x0040;  // Bit 6 (virtual, generated by ring)
    const uint16_t BTN_RIGHT      = 0x0080;  // Bit 7 (virtual, generated by ring)
    const uint16_t BTN_TRIGGER    = 0x0100;  // Bit 8
    const uint16_t BTN_L1         = 0x0200;  // Bit 9
    const uint16_t BTN_MODE       = 0x0400;  // Bit 10
    const uint16_t BTN_JOYSTICK   = 0x0800;  // Bit 11
}

namespace droid::controller {
    MechRingController* MechRingController::instance = nullptr;

    MechRingController::MechRingController(const char* name, droid::core::System* system,
                                           droid::network::MechNetNode* mechNetNode) :
        Controller(name, system),
        mechNetNode(mechNetNode) {
        
        if (MechRingController::instance != nullptr) {
            logger->log(name, FATAL, "Constructor called more than once!\n");
            while (1);  // Halt (singleton constraint)
        }
        MechRingController::instance = this;
        
        // Initialize RingState structs
        memset(&driveRing, 0, sizeof(RingState));
        memset(&domeRing, 0, sizeof(RingState));
    }

    void MechRingController::init() {
        logger->log(name, INFO, "init - called\n");
        
        // Load configuration
        activeTimeout = config->getInt(name, CONFIG_KEY_MECHRING_ACTIVE_TIMEOUT, 
                                       CONFIG_DEFAULT_MECHRING_ACTIVE_TIMEOUT);
        inactiveTimeout = config->getInt(name, CONFIG_KEY_MECHRING_INACTIVE_TIMEOUT, 
                                         CONFIG_DEFAULT_MECHRING_INACTIVE_TIMEOUT);
        deadbandX = config->getInt(name, CONFIG_KEY_MECHRING_DEADBAND_X, 
                                   CONFIG_DEFAULT_MECHRING_DEADBAND);
        deadbandY = config->getInt(name, CONFIG_KEY_MECHRING_DEADBAND_Y, 
                                   CONFIG_DEFAULT_MECHRING_DEADBAND);
        
        // Init triggerMap with defaults from MechRingTrigger.map
        triggerMap.clear();
        #include "settings/MechRingTrigger.map"
        
        // Load config overrides for trigger mappings
        for (const auto& mapEntry : triggerMap) {
            const char* trigger = mapEntry.first.c_str();
            const char* action = mapEntry.second.c_str();
            String override = config->getString(name, trigger, action);
            if (override != action) {
                triggerMap[trigger] = override;
            }
        }
        
        // Initialize ring states
        memset(&driveRing, 0, sizeof(RingState));
        memset(&domeRing, 0, sizeof(RingState));
        // lastMsgTime == 0 means "never seen" (no messages received yet)
        driveRing.lastMsgTime = 0;
        domeRing.lastMsgTime = 0;
        
        faultState = false;
        isCritical = false;
    }

    void MechRingController::factoryReset() {
        config->clear(name);
        config->putInt(name, CONFIG_KEY_MECHRING_ACTIVE_TIMEOUT, 
                       CONFIG_DEFAULT_MECHRING_ACTIVE_TIMEOUT);
        config->putInt(name, CONFIG_KEY_MECHRING_INACTIVE_TIMEOUT, 
                       CONFIG_DEFAULT_MECHRING_INACTIVE_TIMEOUT);
        config->putInt(name, CONFIG_KEY_MECHRING_DEADBAND_X, 
                       CONFIG_DEFAULT_MECHRING_DEADBAND);
        config->putInt(name, CONFIG_KEY_MECHRING_DEADBAND_Y, 
                       CONFIG_DEFAULT_MECHRING_DEADBAND);
        
        // Save default trigger mappings
        triggerMap.clear();
        #include "settings/MechRingTrigger.map"
        for (const auto& mapEntry : triggerMap) {
            const char* trigger = mapEntry.first.c_str();
            const char* action = mapEntry.second.c_str();
            config->putString(name, trigger, action);
        }
    }

    void MechRingController::task() {
        // Update connection status from MechNet
        updateRingConnectionStatus();
        
        // Check for timeouts
        faultCheck();
    }

    void MechRingController::logConfig() {
        logger->log(name, INFO, "Config %s = %s\n", 
                    CONFIG_KEY_MECHRING_ACTIVE_TIMEOUT, 
                    config->getString(name, CONFIG_KEY_MECHRING_ACTIVE_TIMEOUT, "").c_str());
        logger->log(name, INFO, "Config %s = %s\n", 
                    CONFIG_KEY_MECHRING_INACTIVE_TIMEOUT,
                    config->getString(name, CONFIG_KEY_MECHRING_INACTIVE_TIMEOUT, "").c_str());
        logger->log(name, INFO, "Config %s = %s\n", 
                    CONFIG_KEY_MECHRING_DEADBAND_X,
                    config->getString(name, CONFIG_KEY_MECHRING_DEADBAND_X, "").c_str());
        logger->log(name, INFO, "Config %s = %s\n", 
                    CONFIG_KEY_MECHRING_DEADBAND_Y,
                    config->getString(name, CONFIG_KEY_MECHRING_DEADBAND_Y, "").c_str());
        
        // Log trigger mappings
        for (const auto& mapEntry : triggerMap) {
            const char* trigger = mapEntry.first.c_str();
            logger->log(name, INFO, "Config %s = %s\n", 
                        trigger, config->getString(name, trigger, "").c_str());
        }
    }

    void MechRingController::failsafe() {
        // NOOP - Brain handles emergency stop via droidState->stickEnable = false
    }

    void MechRingController::setCritical(bool isCritical) {
        this->isCritical = isCritical;
    }

    int8_t MechRingController::getJoystickPosition(Joystick stick, Axis axis) {
        bool driveSeen = driveRing.lastMsgTime != 0;
        bool domeSeen = domeRing.lastMsgTime != 0;

        // Select ring based on joystick.
        // Normal mapping: RIGHT=DriveRing, LEFT=DomeRing.
        // Single-ring fallback: if DriveRing has never been seen but DomeRing has,
        // allow DomeRing to drive (RIGHT stick). LEFT stick is disabled in this mode
        // to avoid dome motion being coupled to driving.
        RingState* ring = nullptr;
        if (stick == RIGHT) {
            if (driveSeen) {
                ring = &driveRing;
            } else if (domeSeen) {
                ring = &domeRing;
            } else {
                return 0;
            }
        } else {
            if (domeSeen && driveSeen) {
                ring = &domeRing;
            } else {
                return 0;
            }
        }
        
        // Get raw value
        int8_t rawValue = (axis == X) ? ring->joystick_x : ring->joystick_y;
        
        // Apply deadband
        int8_t deadband = (axis == X) ? deadbandX : deadbandY;
        if (abs(rawValue) < deadband) {
            return 0;
        }
        
        // Convert -128/+127 → -100/+100
        int16_t scaled = (rawValue * 100) / 127;
        return constrain(scaled, -100, 100);
    }

    String MechRingController::getAction() {
        String trigger = getTrigger();
        if (trigger.length() == 0) {
            return "";
        }
        
        // Lookup in triggerMap
        auto it = triggerMap.find(trigger);
        if (it != triggerMap.end()) {
            logger->log(name, DEBUG, "Trigger: %s -> Action: %s\n", 
                        trigger.c_str(), it->second.c_str());
            return it->second;
        }
        
        return "";
    }

    void MechRingController::handleRingMessage(const String& sender, const String& message) {
        // Route to correct ring based on sender prefix
        if (sender.startsWith("DriveRing")) {
            parseRingMessage(message, driveRing);
            strncpy(driveRing.uniqueName, sender.c_str(), sizeof(driveRing.uniqueName) - 1);
            driveRing.uniqueName[sizeof(driveRing.uniqueName) - 1] = '\0';
        } else if (sender.startsWith("DomeRing")) {
            parseRingMessage(message, domeRing);
            strncpy(domeRing.uniqueName, sender.c_str(), sizeof(domeRing.uniqueName) - 1);
            domeRing.uniqueName[sizeof(domeRing.uniqueName) - 1] = '\0';
        } else {
            logger->log(name, WARN, "Unknown ring sender: %s\n", sender.c_str());
        }
    }

    void MechRingController::parseRingMessage(const String& msg, RingState& ring) {
        if (!msg.startsWith("S:")) {
            logger->log(name, DEBUG, "Invalid message format: %s\n", msg.c_str());
            return;
        }
        
        int x, y;
        unsigned int buttons;
        
        // Parse: S:<x>,<y>,<hex>
        int parsed = sscanf(msg.c_str() + 2, "%d,%d,%x", &x, &y, &buttons);
        
        if (parsed == 3) {
            ring.joystick_x = constrain(x, -128, 127);
            ring.joystick_y = constrain(y, -128, 127);
            ring.buttonState = buttons & 0xFFFF;  // 16-bit mask
            ring.lastMsgTime = millis();
            
            logger->log(name, DEBUG, "Parsed %s: X=%d, Y=%d, BTN=0x%04X\n",
                        ring.uniqueName, ring.joystick_x, ring.joystick_y, 
                        ring.buttonState);
        } else {
            logger->log(name, WARN, "Failed to parse message: %s\n", msg.c_str());
        }
    }

    void MechRingController::updateRingConnectionStatus() {
        if (!mechNetNode || !mechNetNode->isInitialized()) {
            driveRing.isConnected = false;
            domeRing.isConnected = false;
            return;
        }
        
        // Check if ring nodes are connected via MechNet
        driveRing.isConnected = (strlen(driveRing.uniqueName) > 0) && 
                                mechNetNode->isNodeConnected(driveRing.uniqueName);
        domeRing.isConnected = (strlen(domeRing.uniqueName) > 0) && 
                               mechNetNode->isNodeConnected(domeRing.uniqueName);
    }

    void MechRingController::faultCheck() {
        uint32_t timeout = isCritical ? activeTimeout : inactiveTimeout;
        unsigned long now = millis();

        bool driveSeen = driveRing.lastMsgTime != 0;
        bool domeSeen = domeRing.lastMsgTime != 0;
        
        // Check DriveRing timeout
        if (driveSeen && ((now - driveRing.lastMsgTime) > timeout)) {
            if (!faultState) {
                faultState = true;
                droidState->stickEnable = false;
                logger->log(name, ERROR, "EMERGENCY STOP: DriveRing timeout (%ums)\n", timeout);
            }
            return;  // Don't check DomeRing if DriveRing timed out
        }
        
        // Check DomeRing timeout
        if (domeSeen && ((now - domeRing.lastMsgTime) > timeout)) {
            if (!faultState) {
                faultState = true;
                droidState->stickEnable = false;
                logger->log(name, ERROR, "EMERGENCY STOP: DomeRing timeout (%ums)\n", timeout);
            }
            return;
        }
        
        // No ring timeouts detected - clear fault state if recovering.
        // (Do not require both rings; allow recovery when operating with a single ring.)
        if (faultState) {
            faultState = false;
            logger->log(name, INFO, "Ring controllers reconnected\n");
            // User must manually re-enable stick control for safety
        }
    }

    String MechRingController::getTrigger() {
        bool driveSeen = driveRing.lastMsgTime != 0;
        bool domeSeen = domeRing.lastMsgTime != 0;

        uint16_t driveButtons = driveRing.buttonState;
        uint16_t domeButtons = domeRing.buttonState;

        // Single-ring fallback: if only one ring has ever been seen, treat its buttons as both sides
        // so the existing dual-ring trigger patterns can still resolve.
        if (driveSeen && !domeSeen) {
            domeButtons = driveButtons;
        } else if (!driveSeen && domeSeen) {
            driveButtons = domeButtons;
        }
        
        // Left button (A/B/C/D) + Right direction (Up/Down/Left/Right)
        // Pattern: Left trigger NOT pressed, Left button pressed, Right trigger NOT pressed, Right direction pressed
        
        // LA_R* combinations (Left A + Right directions)
        if (!(domeButtons & BTN_L1) &&!(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_A) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_UP)) {
            return "LA_Rup";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_A) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_DOWN)) {
            return "LA_Rdown";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_A) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_LEFT)) {
            return "LA_Rleft";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_A) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_RIGHT)) {
            return "LA_Rright";
        }
        
        // LB_R* combinations (Left B + Right directions)
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_B) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_UP)) {
            return "LB_Rup";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_B) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_DOWN)) {
            return "LB_Rdown";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_B) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_LEFT)) {
            return "LB_Rleft";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_B) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_RIGHT)) {
            return "LB_Rright";
        }
        
        // LC_R* combinations (Left C + Right directions)
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_C) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_UP)) {
            return "LC_Rup";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_C) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_DOWN)) {
            return "LC_Rdown";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_C) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_LEFT)) {
            return "LC_Rleft";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_C) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_RIGHT)) {
            return "LC_Rright";
        }
        
        // LD_R* combinations (Left D + Right directions)
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_D) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_UP)) {
            return "LD_Rup";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_D) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_DOWN)) {
            return "LD_Rdown";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_D) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_LEFT)) {
            return "LD_Rleft";
        }
        if (!(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_D) && 
            !(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_RIGHT)) {
            return "LD_Rright";
        }
        
        // Right button (A/B/C/D) + Left direction (Up/Down/Left/Right)
        // Pattern: Right trigger NOT pressed, Right button pressed, Left trigger NOT pressed, Left direction pressed
        
        // RA_L* combinations (Right A + Left directions)
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_A) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_UP)) {
            return "RA_Lup";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_A) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_DOWN)) {
            return "RA_Ldown";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_A) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_LEFT)) {
            return "RA_Lleft";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_A) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_RIGHT)) {
            return "RA_Lright";
        }
        
        // RB_L* combinations (Right B + Left directions)
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_B) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_UP)) {
            return "RB_Lup";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_B) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_DOWN)) {
            return "RB_Ldown";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_B) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_LEFT)) {
            return "RB_Lleft";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_B) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_RIGHT)) {
            return "RB_Lright";
        }
        
        // RC_L* combinations (Right C + Left directions)
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_C) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_UP)) {
            return "RC_Lup";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_C) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_DOWN)) {
            return "RC_Ldown";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_C) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_LEFT)) {
            return "RC_Lleft";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_C) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_RIGHT)) {
            return "RC_Lright";
        }
        
        // RD_L* combinations (Right D + Left directions)
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_D) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_UP)) {
            return "RD_Lup";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_D) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_DOWN)) {
            return "RD_Ldown";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_D) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_LEFT)) {
            return "RD_Lleft";
        }
        if (!(driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_D) && 
            !(domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_RIGHT)) {
            return "RD_Lright";
        }
        
        // L*_LL1* combinations (Left L1 + Left ABCD)
        if ((domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_A)) {
            return "LA_LL1";
        }
        if ((domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_B)) {
            return "LB_LL1";
        }
        if ((domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_C)) {
            return "LC_LL1";
        }
        if ((domeButtons & BTN_L1) && !(domeButtons & BTN_TRIGGER) && (domeButtons & BTN_D)) {
            return "LD_LL1";
        }
        
        // R*_RL1* combinations (Right L1 + Right ABCD)
        if ((driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_A)) {
            return "RA_RL1";
        }
        if ((driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_B)) {
            return "RB_RL1";
        }
        if ((driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_C)) {
            return "RC_RL1";
        }
        if ((driveButtons & BTN_L1) && !(driveButtons & BTN_TRIGGER) && (driveButtons & BTN_D)) {
            return "RD_RL1";
        }
        
        return "";  // No trigger pattern matched
    }
}
