//#define BUILD_FOR_DEBUGGER

//PCA9685PWM Config
#define PCA9685_I2C_ADDRESS 0x40
#define PCA9685_OUTPUT_ENABLE_PIN 15
#define PCA9685_OSC_FREQUENCY 27000000

//DomeMgr Motor config
#define PWMSERVICE_DOME_MOTOR_OUT1 0
#define PWMSERVICE_DOME_MOTOR_OUT2 1
#define DOMEMOTOR_POWER_RAMP 10.0

//Stream configurations
#define LOGGER_STREAM Serial
#define LOGGER_STREAM_SETUP Serial.begin(115200)
#define DOME_STREAM LOGGER_STREAM
#define DOME_STREAM_SETUP
#define BODY_STREAM LOGGER_STREAM
#define BODY_STREAM_SETUP
#define HCR_STREAM LOGGER_STREAM
#define HCR_STREAM_SETUP

//DualSonyMoveController
#define CONTROLLER_DEADBAND 20
#define CONFIG_DEFAULT_MAC                  "XX:XX:XX:XX:XX:XX"
#define CONFIG_DEFAULT_SONY_RIGHT_MAC       CONFIG_DEFAULT_MAC
#define CONFIG_DEFAULT_SONY_ALT_RIGHT_MAC   CONFIG_DEFAULT_MAC
#define CONFIG_DEFAULT_SONY_LEFT_MAC        CONFIG_DEFAULT_MAC
#define CONFIG_DEFAULT_SONY_ALT_LEFT_MAC    CONFIG_DEFAULT_MAC
